/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.CurrentTaskContrller;
import Models.CurrentTask;

/**
 *
 * @author AKILA KASUN
 */
public class AddTask extends javax.swing.JFrame {

    CurrentTask cob ;
    CurrentTaskContrller ccob ;
    public AddTask() {
        initComponents();
        ccob = new CurrentTaskContrller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcustomerTP1 = new javax.swing.JTextField();
        txtCollecteddate = new javax.swing.JTextField();
        txtcustomername = new javax.swing.JTextField();
        comboxtaskType = new javax.swing.JComboBox<>();
        txtAdddate = new javax.swing.JTextField();
        txtcumsomerID1 = new javax.swing.JTextField();
        txtcumsomername = new javax.swing.JLabel();
        btnaddtask = new javax.swing.JButton();
        btnaddcustomer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtcustomerTP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 220, 30));
        jPanel1.add(txtCollecteddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 220, 30));
        jPanel1.add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 220, 30));

        comboxtaskType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboxtaskType, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 220, 30));
        jPanel1.add(txtAdddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 220, 30));
        jPanel1.add(txtcumsomerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 220, 30));

        txtcumsomername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/theekshanaAddtask.png"))); // NOI18N
        jPanel1.add(txtcumsomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnaddtask.setText("add task");
        btnaddtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddtask, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 80, -1));

        btnaddcustomer.setText("add customer");
        btnaddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 90, -1));

        jButton1.setText("search");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtaskActionPerformed
        String AddDate  = txtAdddate.getText();
        String Collecteddate = txtCollecteddate.getText();  
        String selectedTask  = (String)comboxtaskType.getSelectedItem();
        double totalPayement ;
        double advancedPayment ;
        double balance ;
        String status ;
        String EmpID
    }//GEN-LAST:event_btnaddtaskActionPerformed

    private void btnaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddcustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcustomer;
    private javax.swing.JButton btnaddtask;
    private javax.swing.JComboBox<String> comboxtaskType;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdddate;
    private javax.swing.JTextField txtCollecteddate;
    private javax.swing.JTextField txtcumsomerID1;
    private javax.swing.JLabel txtcumsomername;
    private javax.swing.JTextField txtcustomerTP1;
    private javax.swing.JTextField txtcustomername;
    // End of variables declaration//GEN-END:variables
}
