/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.CurrentTaskContrller;
import Controllers.PaymentController;
import Controllers.CustomerController;
import Models.CurrentTask;
import Models.Customer;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;

/**
 *
 * @author AKILA KASUN
 */
public class AddTask2 extends javax.swing.JFrame {

    CurrentTask cob ;
    CurrentTaskContrller ccob ;
    CustomerController cco ;
    Customer co ;
    DBconnector dob ;
    ResultSet rs ;
    PaymentController py ;
    public AddTask2() {
        initComponents();
        ccob = new CurrentTaskContrller();
        cco = new CustomerController();
        dob = DBconnector.getSingleInstance() ;
        py = new PaymentController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCusID = new javax.swing.JTextField();
        txtCusEmail = new javax.swing.JTextField();
        txtcustomername = new javax.swing.JTextField();
        txtAddate = new javax.swing.JTextField();
        txtadvancedpayment = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        txtCollecteddate = new javax.swing.JTextField();
        comboxTask = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnaddcustomer = new javax.swing.JButton();
        btnaddtask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 220, 30));
        jPanel1.add(txtCusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 220, 30));
        jPanel1.add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 220, 30));
        jPanel1.add(txtAddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 220, 30));
        jPanel1.add(txtadvancedpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 220, 30));
        jPanel1.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 220, 30));
        jPanel1.add(txtCollecteddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 220, 30));

        comboxTask.setForeground(new java.awt.Color(255, 255, 255));
        comboxTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BatteryReplacing", "BeltRepair", "CustomermizedRepair", "FullWatchRepair", "InnerPartsRepairs" }));
        jPanel1.add(comboxTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 220, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Customer Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 230, 50));

        btnBack.setBackground(new java.awt.Color(102, 0, 153));
        btnBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/theekshanaAddtask3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 90, -1));

        btnaddcustomer.setText("add customer");
        btnaddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 90, -1));

        btnaddtask.setText("add task");
        btnaddtask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddtask, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcustomerActionPerformed
        String cusID = txtCusID.getText();
        String cusname = txtcustomername.getText();
        String cusEmail = txtCusEmail.getText();
        co = cco.AddCustomer(cusname, cusID, cusEmail);
        boolean result= cco.InsterCustomerToDB(co);
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Added to the Database Successfully !" , "info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Adding to the Databse cause Error !" , "Error" , 0);
        }
    }//GEN-LAST:event_btnaddcustomerActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            String cusID = txtCusID.getText();
            rs = dob.ShowExecuteQuary("select *from Customers where CustomerID = '"+cusID+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(rootPane,"Customer found in databse !!" , "Info" , 0);
                txtCusID.setText(rs.getString("CustomerID"));
                txtCusEmail.setText(rs.getString("Email"));
                txtcustomername.setText(rs.getString("CustomerName"));
                
            }
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(rootPane,"Customer not found !!" , "Error" , 0);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnaddtaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtaskActionPerformed
        String AddDate  = txtAddate.getText();
        String Collecteddate = txtCollecteddate.getText();  
        String selectedTask  = (String)comboxTask.getSelectedItem();
        rs = dob.ShowExecuteQuary("select * from currenttask where TaskType = '"+selectedTask+"'");
        double totalPayement = 0 ;
        if(rs.next()){
            totalPayement = rs.getDouble("Price") ;
        }else{
            System.out.println("Price Not found !");
        }
        
        double advancedPayment  = Double.parseDouble(txtadvancedpayment.getText());
        
        double balance  = py.RepairJobs(advancedPayment, totalPayement);
        String status  = "pending";
        String EmpID = txtEmpId.getText();
        String CustomerID = txtCusID.getText();
        
        cob = ccob.addCT(AddDate, Collecteddate, selectedTask, totalPayement, advancedPayment, balance, status, EmpID,CustomerID);
        boolean result = ccob.addtoDB(cob);
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Successfully added to the databse !!" , "Info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Adding to the database Unsuccessfull !!" , "Error" , 0);
        }
    }//GEN-LAST:event_btnaddtaskActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new RepairJobs().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnaddcustomer;
    private javax.swing.JButton btnaddtask;
    private javax.swing.JComboBox<String> comboxTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddate;
    private javax.swing.JTextField txtCollecteddate;
    private javax.swing.JTextField txtCusEmail;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtadvancedpayment;
    private javax.swing.JTextField txtcustomername;
    // End of variables declaration//GEN-END:variables
}
