/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Models.Employee;
import Controllers.EmployeeController;
import javax.swing.JOptionPane;



/**
 *
 * @author AKILA KASUN
 */
public class CreateEmployee extends javax.swing.JFrame {

    Employee emp ;
    EmployeeController empc ;
   
    public CreateEmployee() {
        initComponents();
        empc = new EmployeeController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtempid = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtpossition = new javax.swing.JTextField();
        txtTp = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CyberSouls Corp.", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Californian FB", 3, 12), new java.awt.Color(102, 6, 96))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtempid.setBackground(new java.awt.Color(255, 255, 255));
        txtempid.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtempid.setForeground(new java.awt.Color(0, 0, 0));
        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });
        jPanel1.add(txtempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 330, 30));

        txtSalary.setBackground(new java.awt.Color(255, 255, 255));
        txtSalary.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(0, 0, 0));
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 330, 30));

        txtpossition.setBackground(new java.awt.Color(255, 255, 255));
        txtpossition.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtpossition.setForeground(new java.awt.Color(0, 0, 0));
        txtpossition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpossitionActionPerformed(evt);
            }
        });
        jPanel1.add(txtpossition, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 330, 30));

        txtTp.setBackground(new java.awt.Color(255, 255, 255));
        txtTp.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtTp.setForeground(new java.awt.Color(0, 0, 0));
        txtTp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTpActionPerformed(evt);
            }
        });
        jPanel1.add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 330, 30));

        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 0, 0));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 330, 30));

        txtname.setBackground(new java.awt.Color(255, 255, 255));
        txtname.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 330, 30));

        jButton1.setBackground(new java.awt.Color(102, 0, 153));
        jButton1.setFont(new java.awt.Font("Californian FB", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/createemployee.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1030, 580));

        btnsubmit.setText("submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 471, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void txtpossitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpossitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpossitionActionPerformed

    private void txtTpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTpActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        String name = txtname.getText();
        String Address = txtAddress.getText();
        String Possition = txtpossition.getText();
        String empId = txtempid.getText();
        String tp = txtTp.getText();
        double Salary = Double.parseDouble(txtSalary.getText());
        String username = txtname.getText();
        String Password  = txtempid.getText().substring(0,3);
        Password = Password.concat(txtpossition.getText().substring(0,3));
        Password = Password.concat("@");
        
        emp = empc.addEmp(name, Address, Possition, empId, tp, Salary, username, Password);
        boolean result = empc.addToDBEmp(emp);
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Added to the Database Successfully !" , "info" , 1);
            JOptionPane.showMessageDialog(rootPane,"Your password : "+ Password + "\n" + "Your Username :" + username , "info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Adding to the Databse cause Error !" , "Error" , 0);
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new Login2().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtTp;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpossition;
    // End of variables declaration//GEN-END:variables
}
