/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanoj de silva
 */
public class FinanceReport extends javax.swing.JFrame {

    ResultSet rs;
    ResultSet rs2;
    DBconnector dob;
    double expence = 0 ;
    double income  = 0
    public FinanceReport() {
        initComponents();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFRExpence = new javax.swing.JTable();
        lblTAvenue = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        lblTExpence = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();
        txtTotalExpence = new javax.swing.JTextField();
        txtTotalAvenue = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFrINCOME = new javax.swing.JTable();
        txtTotalIncome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFRExpence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFRExpence);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 200, 330));

        lblTAvenue.setBackground(new java.awt.Color(255, 255, 255));
        lblTAvenue.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        lblTAvenue.setForeground(new java.awt.Color(102, 0, 153));
        lblTAvenue.setText("Total Avenue       :");
        jPanel1.add(lblTAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 150, -1));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        name.setForeground(new java.awt.Color(102, 0, 153));
        name.setText("FINANCE REPORT");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 380, 40));

        lblTExpence.setBackground(new java.awt.Color(255, 255, 255));
        lblTExpence.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        lblTExpence.setForeground(new java.awt.Color(102, 0, 153));
        lblTExpence.setText("Total Expence     :");
        jPanel1.add(lblTExpence, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 140, -1));

        lblIncome.setBackground(new java.awt.Color(255, 255, 255));
        lblIncome.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        lblIncome.setForeground(new java.awt.Color(102, 0, 153));
        lblIncome.setText("Total Income       :");
        jPanel1.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 150, -1));

        txtTotalExpence.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalExpence.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtTotalExpence.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalExpence.setBorder(null);
        jPanel1.add(txtTotalExpence, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 220, -1));

        txtTotalAvenue.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalAvenue.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtTotalAvenue.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalAvenue.setBorder(null);
        jPanel1.add(txtTotalAvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 220, -1));

        btnRefresh1.setBackground(new java.awt.Color(102, 0, 153));
        btnRefresh1.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("REFRESH");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        btnBack.setBackground(new java.awt.Color(102, 0, 153));
        btnBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        tblFrINCOME.setBackground(new java.awt.Color(255, 255, 255));
        tblFrINCOME.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        tblFrINCOME.setForeground(new java.awt.Color(0, 0, 0));
        tblFrINCOME.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InvoiceNO", "TotalPrice"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFrINCOME);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 200, 330));

        txtTotalIncome.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalIncome.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtTotalIncome.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalIncome.setBorder(null);
        jPanel1.add(txtTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blank.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) tblFRExpence.getModel();
        DefaultTableModel tblModel2 = (DefaultTableModel) tblFrINCOME.getModel();
        rs = dob.ShowExecuteQuary("select OrderID , TotalAmount from expence");
        rs2 = dob.ShowExecuteQuary("select InvoiceNo , TotalPrice from payment");
        while(rs.next()){
            String orderID = rs.getString("OderID");
            double amount = rs.getDouble("TotalAmount");
            expence += amount ;
            tblModel.addRow(new Object[]{orderID,amount});
        }
        while(rs2.next()){
            String inNO = rs.getString("InvoiceNO");
            double tPrice = rs.getDouble("TotalPrice");
            income += tPrice ;
            tblModel2.addRow(new Object[] {inNO,tPrice});
        }
        txtTotalExpence.setText(Double.toString(expence));
        txtTotalIncome.setText(Double.toString(income));
        double avenue = income - expence ;
        txtTotalAvenue.setText(Double.toString(avenue));
        
                
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MainMenue().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblTAvenue;
    private javax.swing.JLabel lblTExpence;
    private javax.swing.JLabel name;
    private javax.swing.JTable tblFRExpence;
    private javax.swing.JTable tblFrINCOME;
    private javax.swing.JTextField txtTotalAvenue;
    private javax.swing.JTextField txtTotalExpence;
    private javax.swing.JTextField txtTotalIncome;
    // End of variables declaration//GEN-END:variables
}
