/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author AKILA KASUN
 */
public class Login3 extends javax.swing.JFrame {

    /**
     * Creates new form Login3
     */
    public Login3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblforgetpswrd1 = new javax.swing.JLabel();
        chckboxshowpasswrd = new javax.swing.JCheckBox();
        lblcreateacc = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpswd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btncreataccnt = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnforgetpswrd = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblforgetpswrd1.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblforgetpswrd1.setForeground(new java.awt.Color(102, 0, 153));
        lblforgetpswrd1.setText("      Forget Password");
        jPanel1.add(lblforgetpswrd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 130, 30));

        chckboxshowpasswrd.setText("Show Password");
        chckboxshowpasswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckboxshowpasswrdActionPerformed(evt);
            }
        });
        jPanel1.add(chckboxshowpasswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 120, -1));

        lblcreateacc.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblcreateacc.setForeground(new java.awt.Color(102, 0, 153));
        lblcreateacc.setText("          Create Account");
        jPanel1.add(lblcreateacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 140, 30));

        txtusername.setBorder(null);
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 160, 20));

        txtpswd.setBorder(null);
        txtpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpswdActionPerformed(evt);
            }
        });
        jPanel1.add(txtpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sewmini login3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btncreataccnt.setText("create acccount");
        btncreataccnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreataccntActionPerformed(evt);
            }
        });
        jPanel1.add(btncreataccnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 130, 30));

        btnlogin.setText("login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 371, 130, 30));

        btnforgetpswrd.setText("forget password");
        btnforgetpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetpswrdActionPerformed(evt);
            }
        });
        jPanel1.add(btnforgetpswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 110, 30));

        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpswdActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void chckboxshowpasswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckboxshowpasswrdActionPerformed

        if(chckboxshowpasswrd.isSelected()){
            txtpswd.setEchoChar((char)0);
        }
        else{
            
            txtpswd.setEchoChar('*');
        }
    }//GEN-LAST:event_chckboxshowpasswrdActionPerformed

    private void btncreataccntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreataccntActionPerformed
        CreateEmployee E = new CreateEmployee();
        E.show();
        dispose();
    }//GEN-LAST:event_btncreataccntActionPerformed

    private void btnforgetpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetpswrdActionPerformed
        Forgetpassword2 FP = new Forgetpassword2();
        
        FP.show();
        dispose();
    }//GEN-LAST:event_btnforgetpswrdActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreataccnt;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforgetpswrd;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox chckboxshowpasswrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcreateacc;
    private javax.swing.JLabel lblforgetpswrd1;
    private javax.swing.JPasswordField txtpswd;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
