/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.UserLoginController;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;

/**
 *
 * @author AKILA KASUN
 */
public class Login2 extends javax.swing.JFrame {

    DBconnector dob ;
    ResultSet rs ;
    UserLoginController ulc;
    public Login2() {
        initComponents();
        ulc = new UserLoginController();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblforgetpswrd = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblcreateacc = new javax.swing.JLabel();
        chkShwpwd = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btncreataccnt = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        btnforgetpswrd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblforgetpswrd.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblforgetpswrd.setForeground(new java.awt.Color(102, 0, 153));
        lblforgetpswrd.setText("      Forget Password");
        jPanel1.add(lblforgetpswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 170, 30));

        txtusername.setBorder(null);
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 160, -1));

        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 160, -1));

        lblcreateacc.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblcreateacc.setForeground(new java.awt.Color(102, 0, 153));
        lblcreateacc.setText("          Create Account");
        jPanel1.add(lblcreateacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 170, 30));

        chkShwpwd.setBackground(new java.awt.Color(255, 255, 255));
        chkShwpwd.setForeground(new java.awt.Color(102, 0, 153));
        chkShwpwd.setText("Show Password");
        chkShwpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShwpwdActionPerformed(evt);
            }
        });
        jPanel1.add(chkShwpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("CyberSouls.corp.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 110, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sewminilogin (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnlogin.setText("login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 371, 130, 30));

        btnexit.setText("exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 130, 30));

        btncreataccnt.setText("create acccount");
        btncreataccnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreataccntActionPerformed(evt);
            }
        });
        jPanel1.add(btncreataccnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 120, -1));

        btnadmin.setText("admin");
        jPanel1.add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 70, 30));

        btnforgetpswrd.setText("forget password");
        btnforgetpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgetpswrdActionPerformed(evt);
            }
        });
        jPanel1.add(btnforgetpswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 110, -1));

        jButton1.setText("user");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void chkShwpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShwpwdActionPerformed
        if(chkShwpwd.isSelected()){
            txtPassword.setEchoChar((char)0);
        }else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShwpwdActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String Username = txtusername.getText();
        String Password = String.valueOf(txtPassword.getPassword()) ;
        
        rs = dob.ShowExecuteQuary("select * from employee where Username = '"+Username+"' ");
        if(rs.next()){
            String pwd = rs.getString("Password");
            if(pwd.equals(Password)){
               JOptionPane.showMessageDialog(rootPane,"Login Successfull !" , "info", 1); 
               new MainMenue().setVisible(true);
               this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Password Not Found !" , "Error", 0);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Username Not Found !" , "Error", 0);
        }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnforgetpswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgetpswrdActionPerformed
        new Forgetpassword2().setVisible(true);
        
    }//GEN-LAST:event_btnforgetpswrdActionPerformed

    private void btncreataccntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreataccntActionPerformed
        new CreateEmployee().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncreataccntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btncreataccnt;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnforgetpswrd;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox chkShwpwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcreateacc;
    private javax.swing.JLabel lblforgetpswrd;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
