/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author AKILA KASUN
 */
public class MainMenue extends javax.swing.JFrame {

    /**
     * Creates new form MainMenue
     */
    public MainMenue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btndirrectsales = new javax.swing.JButton();
        btnstocks = new javax.swing.JButton();
        btnfinancereport = new javax.swing.JButton();
        btnemployee = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnrepairjobs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainmenu (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btndirrectsales.setText("dirrect sales");
        btndirrectsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndirrectsalesActionPerformed(evt);
            }
        });
        jPanel1.add(btndirrectsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 200, 40));

        btnstocks.setText("stocks");
        btnstocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstocksActionPerformed(evt);
            }
        });
        jPanel1.add(btnstocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 200, 40));

        btnfinancereport.setText("finance report");
        jPanel1.add(btnfinancereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 200, 40));

        btnemployee.setText("employee");
        btnemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 200, 40));

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 110, 30));

        btnrepairjobs.setText("repair jobs");
        btnrepairjobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrepairjobsActionPerformed(evt);
            }
        });
        jPanel1.add(btnrepairjobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeeActionPerformed
        Employee E = new Employee();
        E.show();
        dispose();
    }//GEN-LAST:event_btnemployeeActionPerformed

    private void btnstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstocksActionPerformed
        Stocks3 S = new Stocks3();
        S.show();
        dispose();
    }//GEN-LAST:event_btnstocksActionPerformed

    private void btndirrectsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndirrectsalesActionPerformed
       Sales Sa = new Sales();
       Sa.show();
       dispose();
    }//GEN-LAST:event_btndirrectsalesActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
      
      Login3 b = new Login3();
      b.setVisible(true);
      
      this.setVisible(false);
      
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnrepairjobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrepairjobsActionPerformed
        RepairJobs rj = new RepairJobs();
        rj.show();
        dispose();
    }//GEN-LAST:event_btnrepairjobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndirrectsales;
    private javax.swing.JButton btnemployee;
    private javax.swing.JButton btnfinancereport;
    private javax.swing.JButton btnrepairjobs;
    private javax.swing.JButton btnstocks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
