/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.EmployeeController;
import Models.Employee;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanoj de silva
 */
public class ManageEmployee extends javax.swing.JFrame {

    Employee eob ;
    EmployeeController ecob ;
    public ManageEmployee() {
        initComponents();
        ecob = new EmployeeController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPossition = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        txtTp = new javax.swing.JTextField();
        txtSalry = new javax.swing.JTextField();
        txtUername = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnTbL = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPossition.setBackground(new java.awt.Color(255, 255, 255));
        txtPossition.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtPossition.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPossition, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 280, -1));

        txtadress.setBackground(new java.awt.Color(255, 255, 255));
        txtadress.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtadress.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 280, -1));

        txtTp.setBackground(new java.awt.Color(255, 255, 255));
        txtTp.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtTp.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 280, -1));

        txtSalry.setBackground(new java.awt.Color(255, 255, 255));
        txtSalry.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtSalry.setForeground(new java.awt.Color(0, 0, 0));
        txtSalry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalryActionPerformed(evt);
            }
        });
        jPanel1.add(txtSalry, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 280, -1));

        txtUername.setBackground(new java.awt.Color(255, 255, 255));
        txtUername.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtUername.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtUername, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 280, -1));

        txtEmpID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpID.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtEmpID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 280, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        btnTbL.setBackground(new java.awt.Color(255, 255, 255));
        btnTbL.setFont(new java.awt.Font("Californian FB", 1, 20)); // NOI18N
        btnTbL.setForeground(new java.awt.Color(102, 51, 255));
        btnTbL.setText("Show In Table View....");
        btnTbL.setBorder(null);
        btnTbL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbLActionPerformed(evt);
            }
        });
        jPanel1.add(btnTbL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 200, -1));

        btnBack.setBackground(new java.awt.Color(102, 0, 153));
        btnBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MicrosoftTeams-image (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 570));

        btndelete.setText("jButton1");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 120, -1));

        btnUpdate.setText("jButton2");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalryActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String empid = txtEmpID.getText();
        String possition = txtPossition.getText();
        String address = txtadress.getText();
        String tp = txtTp.getText();
        String username = txtUername.getText();
        double salary = Double.parseDouble(txtSalry.getText());
        
        
        boolean result = ecob.UpdateDBEmp(username, address, possition, empid, tp, salary);
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Successfully update the databse !!" , "Info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Database Update Unsuccessfull !!" , "Error" , 0);
        }        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String empid = txtEmpID.getText();
        
        boolean result = ecob.deleteDBEmp(empid);
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Successfully delete from the databse !!" , "Info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Delete From The Database Was Unsuccessfull !!" , "Error" , 0);
        } 
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnTbLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbLActionPerformed
        new EmployeeTBLview().setVisible(true);
    }//GEN-LAST:event_btnTbLActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Views.Employee().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTbL;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtPossition;
    private javax.swing.JTextField txtSalry;
    private javax.swing.JTextField txtTp;
    private javax.swing.JTextField txtUername;
    private javax.swing.JTextField txtadress;
    // End of variables declaration//GEN-END:variables
}
