/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;



public class orderstock extends javax.swing.JFrame {

    DBconnector dob ;
    ResultSet rs ;
    public orderstock() {
        initComponents();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        txtsupid = new javax.swing.JTextField();
        txtsppart = new javax.swing.JTextField();
        txtwatches = new javax.swing.JTextField();
        txtotalamount = new javax.swing.JTextField();
        comboxstype = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 250, -1));

        txtsupid.setBackground(new java.awt.Color(255, 255, 255));
        txtsupid.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtsupid.setForeground(new java.awt.Color(0, 0, 0));
        txtsupid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupidActionPerformed(evt);
            }
        });
        jPanel1.add(txtsupid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 250, -1));

        txtsppart.setBackground(new java.awt.Color(255, 255, 255));
        txtsppart.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtsppart.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtsppart, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 250, -1));

        txtwatches.setBackground(new java.awt.Color(255, 255, 255));
        txtwatches.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtwatches.setForeground(new java.awt.Color(0, 0, 0));
        txtwatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwatchesActionPerformed(evt);
            }
        });
        jPanel1.add(txtwatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 250, -1));

        txtotalamount.setBackground(new java.awt.Color(255, 255, 255));
        txtotalamount.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        txtotalamount.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtotalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 250, -1));

        comboxstype.setBackground(new java.awt.Color(255, 255, 255));
        comboxstype.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        comboxstype.setForeground(new java.awt.Color(0, 0, 0));
        comboxstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Watches", "SpareParts" }));
        jPanel1.add(comboxstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 250, -1));

        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/myOrder.png"))); // NOI18N
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 80, -1));

        btnorder.setText("jButton1");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsupidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupidActionPerformed

    private void txtwatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwatchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwatchesActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        String stocktype = (String) comboxstype.getSelectedItem();
        int qunatity = Integer.parseInt(txtQuantity.getText());
        String supid = txtsupid.getText();
        String Watches = txtwatches.getText();
        String sp = txtsppart.getText();
        String totalAmount = txtotalamount.getText();
        String orderID = supid.substring(0,3);
        
        if(stocktype.equals("Watches")){
            orderID = orderID.concat(Watches.substring(0,3));
            boolean result = dob.ExecuteQuary("insert into expence values ('Watches','"+orderID+"',"+qunatity+" , "+totalAmount+")");
            if(result){
                    JOptionPane.showMessageDialog(rootPane,"Successfully Added to  the databse !!" , "Info" , 1);
             }else{
                    JOptionPane.showMessageDialog(rootPane,"Adding to the Database was Unsuccessfull !!" , "Error" , 0);
            }
            boolean result2 = dob.ExecuteQuary("insert into orders values ('"+orderID+"','"+supid+"',"+qunatity+",'"+Watches+"',"+totalAmount+")");
            if(result2){
                    JOptionPane.showMessageDialog(rootPane,"Successfully Added to  the order databse  !!" , "Info" , 1);
             }else{
                    JOptionPane.showMessageDialog(rootPane,"Adding to the ORder Database was Unsuccessfull !!" , "Error" , 0);
            }
        }else if(stocktype.equals("SpareParts")){
            orderID = orderID.concat(sp.substring(0,3));
            boolean result = dob.ExecuteQuary("insert into expence values ('SpareParts','"+orderID+"',"+qunatity+" , "+totalAmount+")");
            if(result){
                    JOptionPane.showMessageDialog(rootPane,"Successfully Added to  the databse !!" , "Info" , 1);
             }else{
                    JOptionPane.showMessageDialog(rootPane,"Adding to the Database was Unsuccessfull !!" , "Error" , 0);
            }
            boolean result2 = dob.ExecuteQuary("insert into orders values ('"+orderID+"','"+supid+"',"+qunatity+",'"+sp+"',"+totalAmount+")");
            if(result2){
                    JOptionPane.showMessageDialog(rootPane,"Successfully Added to  the order databse  !!" , "Info" , 1);
             }else{
                    JOptionPane.showMessageDialog(rootPane,"Adding to the ORder Database was Unsuccessfull !!" , "Error" , 0);
            }
        }
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        new Stocks3().setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderstock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnorder;
    private javax.swing.JComboBox<String> comboxstype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtotalamount;
    private javax.swing.JTextField txtsppart;
    private javax.swing.JTextField txtsupid;
    private javax.swing.JTextField txtwatches;
    // End of variables declaration//GEN-END:variables
}
