/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;

/**
 *
 * @author AKILA KASUN
 */
public class OrderSpareParts extends javax.swing.JFrame {

    ResultSet rs;
    DBconnector dob;
    public OrderSpareParts() {
        initComponents();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboxwatchtype = new javax.swing.JComboBox<>();
        comboxquantity = new javax.swing.JComboBox<>();
        comboxspareparts = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnorder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboxwatchtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboxwatchtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 210, 30));

        comboxquantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboxquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 210, 30));

        comboxspareparts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboxspareparts, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 159, 210, 30));

        btnBack.setBackground(new java.awt.Color(102, 0, 153));
        btnBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order spare parts.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnorder.setText("order");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        String spType = (String)comboxspareparts.getSelectedItem();
        String Wtype = (String)comboxwatchtype.getSelectedItem();
        int quantity = Integer.parseInt((String)comboxquantity.getSelectedItem());
        rs = dob.ShowExecuteQuary("select * from spareparts where SPType = '"+spType+"' and WatchType = '"+Wtype+"'");
        if(rs.next()){
            int qnt = rs.getInt("Quantity");
            int nQnt = qnt - quantity ;
            if(nQnt >= 10){
               boolean result = dob.ExecuteQuary("update spareparts set Quantity = "+nQnt+" ");
               if(result){
                   JOptionPane.showMessageDialog(rootPane,"Order Successfull !" , "Info" , 1);
               }else{
                   JOptionPane.showMessageDialog(rootPane,"Order Unsuccessfull !" , "Error" , 0);
               }
            }else if(nQnt < 10){
                JOptionPane.showMessageDialog(rootPane,"Order Unsuccessfull !" , "Error" , 0);
                JOptionPane.showMessageDialog(rootPane," Low Stock Limt " , "Massage" , 3);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"SparePart not Found!!" , "Error" , 0);
        }
    }//GEN-LAST:event_btnorderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new RepairJobs().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderSpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderSpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderSpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderSpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderSpareParts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnorder;
    private javax.swing.JComboBox<String> comboxquantity;
    private javax.swing.JComboBox<String> comboxspareparts;
    private javax.swing.JComboBox<String> comboxwatchtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
