/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;


public class Payment extends javax.swing.JFrame {

    ResultSet rs ;
    DBconnector dob ;
    public Payment() {
        initComponents();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAdddate = new javax.swing.JTextField();
        txtSelectedtask = new javax.swing.JTextField();
        txtInvoiceNo = new javax.swing.JTextField();
        txttotalAmount = new javax.swing.JTextField();
        txtBalToPaid = new javax.swing.JTextField();
        txtPayment = new javax.swing.JTextField();
        txtEmpID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAddInvoice = new javax.swing.JButton();
        btnViewinvoice = new javax.swing.JButton();
        btnAddBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAdddate.setBackground(new java.awt.Color(255, 255, 255));
        txtAdddate.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtAdddate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtAdddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 160, -1));

        txtSelectedtask.setBackground(new java.awt.Color(255, 255, 255));
        txtSelectedtask.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtSelectedtask.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtSelectedtask, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 160, -1));

        txtInvoiceNo.setBackground(new java.awt.Color(255, 255, 255));
        txtInvoiceNo.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtInvoiceNo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtInvoiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 160, -1));

        txttotalAmount.setBackground(new java.awt.Color(255, 255, 255));
        txttotalAmount.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txttotalAmount.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txttotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 160, -1));

        txtBalToPaid.setBackground(new java.awt.Color(255, 255, 255));
        txtBalToPaid.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtBalToPaid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtBalToPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 160, -1));

        txtPayment.setBackground(new java.awt.Color(255, 255, 255));
        txtPayment.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtPayment.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 160, -1));

        txtEmpID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpID.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtEmpID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 160, -1));

        btnBack.setBackground(new java.awt.Color(102, 0, 153));
        btnBack.setFont(new java.awt.Font("Californian FB", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pay.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 580));

        btnSearch.setText("jButton1");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 200, 130, -1));

        btnAddInvoice.setText("jButton2");
        btnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 260, 130, 30));

        btnViewinvoice.setText("jButton3");
        btnViewinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewinvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 320, 120, -1));

        btnAddBill.setText("jButton4");
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String empID = txtEmpID.getText();
        String addDate = txtAdddate.getText();
        String selettask = txtSelectedtask.getText();
                
        rs = dob.ShowExecuteQuary("select * from currenttask where AddDate = '"+addDate+"' , SelectedTask ='"+selettask+"' , EmpId = '"+empID+"' ");
        if(rs.next()){
            txttotalAmount.setText(rs.getString("TotalPayment"));
            txtBalToPaid.setText(rs.getString("Balance"));
        }else{
            JOptionPane.showMessageDialog(rootPane,"Task Not Found" , "Error" , 0);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvoiceActionPerformed
        double totalprice = Double.parseDouble(txttotalAmount.getText());
        
        String empID = txtEmpID.getText();
        String selettask = txtSelectedtask.getText();
        String invoice = selettask.substring(0,3);
        invoice = invoice.concat(empID.substring(0,3));
        txtInvoiceNo.setText(invoice);
        boolean result = dob.ExecuteQuary("insert into payment values ('"+invoice+"','RJ',"+totalprice+" ,"+totalprice+")");
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Successfully added to the databse !!" , "Info" , 1);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Adding to the database Unsuccessfull !!" , "Error" , 0);
        }
    }//GEN-LAST:event_btnAddInvoiceActionPerformed

    private void btnViewinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewinvoiceActionPerformed
         new InvoiceTBL().setVisible(true);
    }//GEN-LAST:event_btnViewinvoiceActionPerformed

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        String empID = txtEmpID.getText();
        String addDate = txtAdddate.getText();
        String selettask = txtSelectedtask.getText();
        boolean result = dob.ExecuteQuary("update currenttask set PaymentStatus = 'completed' where AddDate = '"+addDate+"' , SelectedTask ='"+selettask+"' , EmpId = '"+empID+"'");
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Payment Complete !!" , "Info" , 1);
            new Sales().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Payment Incomplete !!" , "Error" , 0);
        }
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new RepairJobs().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddInvoice;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewinvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdddate;
    private javax.swing.JTextField txtBalToPaid;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtSelectedtask;
    private javax.swing.JTextField txttotalAmount;
    // End of variables declaration//GEN-END:variables
}
