/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author AKILA KASUN
 */
public class prograsbar extends javax.swing.JFrame {

    /**
     * Creates new form prograsbar
     */
    public prograsbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        precentage = new javax.swing.JLabel();
        prograssbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precentage.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        precentage.setForeground(new java.awt.Color(255, 255, 255));
        precentage.setText("100%");
        jPanel1.add(precentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        prograssbar.setForeground(new java.awt.Color(255, 255, 255));
        prograssbar.setBorder(null);
        jPanel1.add(prograssbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 550, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LOADING PAGE1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        prograsbar ti;
        ti = new prograsbar();
        ti.setVisible(true);
        try {
            for(int i = 0 ;i <= 100;i++)
            {
                Thread.sleep(40);
                ti.prograssbar.setValue(i);

                ti.precentage.setText(Integer.toString(i)+ "%");
            }

        }catch (Exception ex1){
            System.out.println("Exception Error!!" + ex1.getMessage());
        }
        new Login2().setVisible(true);
        ti.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precentage;
    private javax.swing.JProgressBar prograssbar;
    // End of variables declaration//GEN-END:variables
}
