/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import javax.swing.ImageIcon;

/**
 *
 * @author AKILA KASUN
 */
public class SpareParts extends javax.swing.JFrame {

    /**
     * Creates new form SpareParts
     */
    public SpareParts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollBar1 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnadd1 = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btndelete1 = new javax.swing.JButton();
        lbltimeticker = new javax.swing.JLabel();
        lblsetyour = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblno = new javax.swing.JLabel();
        comboxitem = new javax.swing.JComboBox<>();
        lblbrand = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbltype = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblwatches = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LBLCLOSE = new javax.swing.JButton();

        jTextField1.setFont(new java.awt.Font("Californian FB", 0, 48)); // NOI18N
        jTextField1.setText("STOCKS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setMinimumSize(new java.awt.Dimension(1024, 576));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadd1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 50));

        btnupdate1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        btnupdate1.setText("Update");
        jPanel1.add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 140, 50));

        btndelete1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        btndelete1.setText("Delete");
        jPanel1.add(btndelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 140, 50));

        lbltimeticker.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        lbltimeticker.setForeground(new java.awt.Color(204, 204, 204));
        lbltimeticker.setText("TIME TICKER ");
        jPanel1.add(lbltimeticker, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 236, 51));

        lblsetyour.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblsetyour.setForeground(new java.awt.Color(204, 204, 204));
        lblsetyour.setText("Set Yout Time In Your Mind");
        jPanel1.add(lblsetyour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 228, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sdsdsd.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sdsdf (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 110, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sdsdf.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 90, 80));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblno.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblno.setText("Spare Part Types");

        comboxitem.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        comboxitem.setMaximumRowCount(20);
        comboxitem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dial", "Crown", "Lug", "Hands", "Crystal", "Case", "Bezel", "Buckle", "Strap", "Bttery ", "Lether Belt", "Steel Belt", "Gold  Steel Belt", "Sub Dial", "Hour Maker", "Wheels", "Date Tape", "Digital Pannel", " " }));
        comboxitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxitemActionPerformed(evt);
            }
        });

        lblbrand.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lblbrand.setText("Spare Part Quantity");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", " " }));

        lbltype.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N
        lbltype.setText("Watch Type");

        jComboBox2.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wrist Watch Men", "Wrist Watch Women", "Wall Clocks", "Pocket Watch ", "Railroad Watch ", "Dress Watch ", "Field Watch ", "Aviator Watch", "Dive Watch ", "Racing Watch ", "Digital Watch ", "Smart Watch ", "Fashion Watch", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(comboxitem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboxitem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 730, 350));

        jPanel4.setBackground(new java.awt.Color(153, 102, 255));

        lblwatches.setFont(new java.awt.Font("Californian FB", 0, 48)); // NOI18N
        lblwatches.setForeground(new java.awt.Color(204, 204, 204));
        lblwatches.setText("Spare Parts");
        lblwatches.setPreferredSize(new java.awt.Dimension(174, 56));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblwatches, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblwatches, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 730, 120));

        LBLCLOSE.setText("X");
        LBLCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBLCLOSEActionPerformed(evt);
            }
        });
        jPanel3.add(LBLCLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void LBLCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBLCLOSEActionPerformed
        this.dispose();
    }//GEN-LAST:event_LBLCLOSEActionPerformed

    private void comboxitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxitemActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpareParts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpareParts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LBLCLOSE;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btndelete1;
    private javax.swing.JButton btnupdate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboxitem;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblbrand;
    private javax.swing.JLabel lblno;
    private javax.swing.JLabel lblsetyour;
    private javax.swing.JLabel lbltimeticker;
    private javax.swing.JLabel lbltype;
    private javax.swing.JLabel lblwatches;
    // End of variables declaration//GEN-END:variables
}
