/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.ResultSet;
import DataBaseConnection.DBconnector;
import javax.swing.JOptionPane;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
/**
 *
 * @author Sanoj de silva
 */
public class SubmitTask extends javax.swing.JFrame {
    
    
   ResultSet rs;
   DBconnector dob ;
   String From = "sanojdesilva24065@gmail.com";
   final String subject = "Time Tiker Watch Repair Workers";
   final String content = "Your Watch is ready \n\n\t TimeTiker-premium";
   final String host = "localhost";
    public SubmitTask() {
        initComponents();
        dob = DBconnector.getSingleInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAdddate = new javax.swing.JTextField();
        txtCusID = new javax.swing.JTextField();
        txtTAsk = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));

        jLabel2.setBackground(new java.awt.Color(102, 0, 153));
        jLabel2.setFont(new java.awt.Font("Californian FB", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("CyberSoul CORP.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 130, 370));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Submit Task");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Task");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, 20));

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Add Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Customer ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        txtAdddate.setBackground(new java.awt.Color(255, 255, 255));
        txtAdddate.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtAdddate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtAdddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        txtCusID.setBackground(new java.awt.Color(255, 255, 255));
        txtCusID.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtCusID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, -1));

        txtTAsk.setBackground(new java.awt.Color(255, 255, 255));
        txtTAsk.setFont(new java.awt.Font("Californian FB", 0, 12)); // NOI18N
        txtTAsk.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtTAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        btnSubmit.setBackground(new java.awt.Color(102, 0, 153));
        btnSubmit.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT TASK");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String Task = txtTAsk.getText();
        String AddDate = txtAdddate.getText();
        
        String CusID = txtCusID.getText();
        
        rs = dob.ShowExecuteQuary("select * from customer where CustomerID = '"+CusID+"'");
        if(rs.next()){
            String to = rs.getString("Email");
            Properties p = new Properties();
            p.put("mail.smtp.auth","true");
            p.put("mail.smtp.starttls.enable","true");
            p.put("mail.smtp.host","smtp.gmail.com");
            p.put("mail.smtp.port","587");
            Session s = Session.getDefaultInstance(p,new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("sanojdesilva24065@gmail.com","Sanoj24065");
                }
            });
            try{
                MimeMessage m = new MimeMessage(s);
                m.setFrom(From);
                m.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                m.setSubject(subject);
                m.setText(content);
                Transport.send(m);
                JOptionPane.showMessageDialog(rootPane,"Successfully Email Send !","Info",1);
                
            }catch(Exception e){
                e.printStackTrace();
            }
            
            
        }else{
            JOptionPane.showMessageDialog(rootPane,"Customer Not Found !","Error",0);
        }
        boolean result = dob.ExecuteQuary("update currenttask set Status = 'Completed' where Selectedtask = '"+Task+"' and AddDate = '"+AddDate+"' ");
        if(result){
            JOptionPane.showMessageDialog(rootPane,"Successfully Updated !","Info",1);
            new CurrentTask().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane,"Update Unsuccessfull  !","Error",0);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmitTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmitTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmitTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmitTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmitTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAdddate;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtTAsk;
    // End of variables declaration//GEN-END:variables
}
